a

diff --git a/html-helloworld/.s2i/bin/assemble b/html-helloworld/.s2i/bin/assemble
--- a/html-helloworld/.s2i/bin/assemble
+++ b/html-helloworld/.s2i/bin/assemble
@@ -1,6 +1,15 @@
 #! /bin/bash
 
-echo "-------------Starting-----------"
-ls -alrt
-cp -Rv ./src ./
+echo "Before Assembling..."
 
+/usr/libexec/s2i/assemble
+
+rc=$?
+
+if [ $rc -eq 0 ]; then
+	echo "After successful assembling"
+else
+	echo "After failed assembling"
+fi
+
+exit $rc
